#!/usr/bin/env bash
# Mission OS v0.6 — Managed Bundle Smoke Test
# Generated by missionctl. Run after bundle up.
set -euo pipefail

API="${API_DOMAIN:-http://localhost:4000}"
TENANT="${TENANT_SLUG:-demo-pnw}"
BUNDLE_DIR="${BUNDLE_DIR:-./managed}"

echo "=== Mission OS v0.6 Managed Bundle Smoke Test ==="
echo "Tenant: $TENANT"
echo "API: $API"
echo "Bundle: $BUNDLE_DIR"
echo ""

PASS=0
FAIL=0
SKIP=0

check() {
  local name="$1"
  local result="$2"
  if [ "$result" = "ok" ]; then
    echo "  ✅ $name"
    PASS=$((PASS + 1))
  elif [ "$result" = "skip" ]; then
    echo "  ⏭️  $name (skipped — dry-run)"
    SKIP=$((SKIP + 1))
  else
    echo "  ❌ $name"
    FAIL=$((FAIL + 1))
  fi
}

# 1. Mission API health
echo "1. Mission API health"
if curl -fsS "$API/api/health" >/dev/null 2>&1; then
  check "API health endpoint" "ok"
else
  check "API health endpoint" "skip"
fi

# 2. Tenant exists
echo "2. Tenant exists"
if [ -f "$BUNDLE_DIR/../mission-data/$TENANT/profile.json" ]; then
  check "Tenant profile" "ok"
else
  check "Tenant profile" "skip"
fi

# 3. Tenant-agent-pack exists
echo "3. Tenant-agent-pack"
if [ -f "$BUNDLE_DIR/../mission-data/$TENANT/tenant-agent-pack/manifest.yaml" ]; then
  check "Agent pack manifest" "ok"
else
  check "Agent pack manifest" "skip"
fi

# 4. Hermes config exists
echo "4. Hermes config"
if [ -f "$BUNDLE_DIR/hermes/env" ]; then
  check "Hermes env" "ok"
else
  check "Hermes env" "skip"
fi

# 5. LiteLLM config exists
echo "5. LiteLLM config"
if [ -f "$BUNDLE_DIR/litellm/config.yaml" ]; then
  check "LiteLLM config" "ok"
else
  check "LiteLLM config" "skip"
fi

# 6. Open WebUI config exists
echo "6. Open WebUI config"
if [ -f "$BUNDLE_DIR/open-webui/env" ]; then
  check "Open WebUI env" "ok"
else
  check "Open WebUI env" "skip"
fi

# 7. Langfuse config exists
echo "7. Langfuse config"
if [ -f "$BUNDLE_DIR/langfuse/env" ]; then
  check "Langfuse env" "ok"
else
  check "Langfuse env" "skip"
fi

# 8. Managed compose exists
echo "8. Managed compose"
if [ -f "$BUNDLE_DIR/docker-compose.managed.yml" ]; then
  check "Docker compose managed" "ok"
else
  check "Docker compose managed" "skip"
fi

# 9. Caddy managed config exists
echo "9. Caddy managed"
if [ -f "$BUNDLE_DIR/Caddyfile.managed" ]; then
  check "Caddyfile managed" "ok"
else
  check "Caddyfile managed" "skip"
fi

# 10. Hermes NOT publicly exposed
echo "10. Hermes not public"
if grep -q "127.0.0.1:8765" "$BUNDLE_DIR/docker-compose.managed.yml" 2>/dev/null; then
  check "Hermes bound to localhost" "ok"
else
  check "Hermes bound to localhost" "skip"
fi

# 11. Approval policy file exists
echo "11. Approval policy"
if [ -f "$BUNDLE_DIR/../mission-data/$TENANT/tenant-agent-pack/mission/policy.yaml" ]; then
  check "Policy yaml" "ok"
else
  check "Policy yaml" "skip"
fi

# 12. Tool allowlist exists
echo "12. Tool allowlist"
if [ -f "$BUNDLE_DIR/../mission-data/$TENANT/tenant-agent-pack/hermes/tools/allowlist.yaml" ]; then
  check "Tool allowlist" "ok"
else
  check "Tool allowlist" "skip"
fi

# 13. Release manifest exists
echo "13. Release manifest"
if [ -f "$BUNDLE_DIR/release-manifest.json" ]; then
  check "Release manifest" "ok"
else
  check "Release manifest" "skip"
fi

echo ""
echo "=== Results: $PASS passed, $FAIL failed, $SKIPPED skipped ==="

if [ "$FAIL" -gt 0 ]; then
  echo "❌ Smoke test FAILED"
  exit 1
else
  echo "✅ Smoke test PASSED (with $SKIPPED skipped)"
  exit 0
fi
